-- MySQL Script generated by MySQL Workbench
-- 03/24/18 21:52:25
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema dbalquiler
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dbalquiler
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dbalquiler` DEFAULT CHARACTER SET utf8 ;
USE `dbalquiler` ;

-- -----------------------------------------------------
-- Table `dbalquiler`.`laptop`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbalquiler`.`laptop` (
  `idlap` INT NOT NULL AUTO_INCREMENT,
  `marca` VARCHAR(20) NULL,
  `modelo` VARCHAR(20) NULL,
  `cantidad` VARCHAR(5) NULL,
  `estado` VARCHAR(20) NULL,
  PRIMARY KEY (`idlap`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbalquiler`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbalquiler`.`usuario` (
  `idusu` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(30) NULL,
  `apellidos` VARCHAR(50) NULL,
  `username` VARCHAR(15) NULL,
  `password` VARCHAR(100) NULL,
  `telefono` VARCHAR(10) NULL,
  `fecha_registro` VARCHAR(10) NULL,
  `tipo` VARCHAR(45) NULL,
  PRIMARY KEY (`idusu`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbalquiler`.`prestamo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbalquiler`.`prestamo` (
  `idpres` INT NOT NULL AUTO_INCREMENT,
  `idlap` INT NULL,
  `idusu` INT NULL,
  `fecha_prestamo` VARCHAR(10) NULL,
  `precio` VARCHAR(10) NULL,
  `fecha_devolucion` VARCHAR(10) NULL,
  PRIMARY KEY (`idpres`),
  INDEX `fk_prestamo_laptop_idx` (`idlap` ASC),
  INDEX `fk_prestamo_usuario_idx` (`idusu` ASC),
  CONSTRAINT `fk_prestamo_laptop`
    FOREIGN KEY (`idlap`)
    REFERENCES `dbalquiler`.`laptop` (`idlap`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_prestamo_usuario`
    FOREIGN KEY (`idusu`)
    REFERENCES `dbalquiler`.`usuario` (`idusu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
